name: CI

on: 
  pull_request:
    paths:
      - 'python-backend/**'

jobs:
  python-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        #   cache: 'pip'
        #   cache-dependency-path: 'python-backend/requirements.txt'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --ignore-glob="*_integration.py"

  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-backend

    steps:
      - uses: actions/checkout@v4
    
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
    
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --output-format=github .
        